import { Event, RecentActivityItem } from '../types';

export function getRandomColor(): string {
  const letters = '0123456789ABCDEF';
  let color = '#';
  for (let i = 0; i < 6; i++) {
    color += letters[Math.floor(Math.random() * 16)];
  }
  return color;
}

export function getLastUpdateDate(events: Event[], recentActivity: RecentActivityItem[] = []): string {
  let lastUpdateDate: Date | null = null;

  // Revisar eventos actuales
  events.forEach(event => {
    const fechaEditado = new Date(event.FechaEditado || event.FechaAgregado || '');
    if (fechaEditado.toString() !== 'Invalid Date' && (!lastUpdateDate || fechaEditado > lastUpdateDate)) {
      lastUpdateDate = fechaEditado;
    }
  });

  // Revisar actividad reciente (incluyendo eliminaciones)
  recentActivity.forEach(item => {
    const fecha = new Date(item.event.FechaEditado || item.event.FechaAgregado || '');
    if (fecha.toString() !== 'Invalid Date' && (!lastUpdateDate || fecha > lastUpdateDate)) {
      lastUpdateDate = fecha;
    }
  });

  return lastUpdateDate 
    ? `${lastUpdateDate.toLocaleDateString('es-ES')} a las ${lastUpdateDate.toLocaleTimeString('es-ES', { hour: '2-digit', minute: '2-digit' })}H`
    : 'N/A';
}

export interface UpdateInfo {
  formatted: string;
  relativeLabel: string;
  /** Tailwind text color class */
  textColor: string;
  /** Tailwind bg + border classes for a pill/badge */
  badgeClasses: string;
}

function getCanaryTime(): Date {
  const now = new Date();
  const utc = now.getTime() + (now.getTimezoneOffset() * 60000);
  return new Date(utc);
}

export function getLastUpdateInfo(events: Event[], recentActivity: RecentActivityItem[] = []): UpdateInfo {
  let lastUpdateDate: Date | null = null;

  events.forEach(event => {
    const fechaEditado = new Date(event.FechaEditado || event.FechaAgregado || '');
    if (fechaEditado.toString() !== 'Invalid Date' && (!lastUpdateDate || fechaEditado > lastUpdateDate)) {
      lastUpdateDate = fechaEditado;
    }
  });

  recentActivity.forEach(item => {
    const fecha = new Date(item.event.FechaEditado || item.event.FechaAgregado || '');
    if (fecha.toString() !== 'Invalid Date' && (!lastUpdateDate || fecha > lastUpdateDate)) {
      lastUpdateDate = fecha;
    }
  });

  const formatted = lastUpdateDate
    ? `${lastUpdateDate.toLocaleDateString('es-ES')} a las ${lastUpdateDate.toLocaleTimeString('es-ES', { hour: '2-digit', minute: '2-digit' })}H`
    : 'N/A';

  if (!lastUpdateDate) {
    return { formatted, relativeLabel: '', textColor: 'text-gray-400', badgeClasses: 'bg-gray-500/20 text-gray-300 border-gray-500/30' };
  }

  const now = getCanaryTime();
  const todayStart = new Date(Date.UTC(now.getFullYear(), now.getMonth(), now.getDate()));
  const updateDayStart = new Date(Date.UTC(lastUpdateDate.getFullYear(), lastUpdateDate.getMonth(), lastUpdateDate.getDate()));
  const diffDays = Math.floor((todayStart.getTime() - updateDayStart.getTime()) / (1000 * 60 * 60 * 24));

  if (diffDays === 0) {
    return { formatted, relativeLabel: 'Hoy', textColor: 'text-emerald-300', badgeClasses: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40' };
  } else if (diffDays === 1) {
    return { formatted, relativeLabel: 'Ayer', textColor: 'text-amber-300', badgeClasses: 'bg-amber-500/20 text-amber-300 border-amber-500/40' };
  } else if (diffDays <= 3) {
    return { formatted, relativeLabel: `Hace ${diffDays} días`, textColor: 'text-orange-300', badgeClasses: 'bg-orange-500/20 text-orange-300 border-orange-500/40' };
  } else if (diffDays <= 7) {
    return { formatted, relativeLabel: `Hace ${diffDays} días`, textColor: 'text-red-300', badgeClasses: 'bg-red-500/20 text-red-300 border-red-500/40' };
  } else {
    return { formatted, relativeLabel: `Hace ${diffDays} días`, textColor: 'text-red-400', badgeClasses: 'bg-red-600/20 text-red-400 border-red-600/40' };
  }
}


export function groupEventsByDay(events: Event[]): { [key: string]: Event[] } {
  const eventsByDay: { [key: string]: Event[] } = {};

  events.forEach(event => {
    const eventDate = new Date(event.day);
    const twoDaysAgo = new Date();
    twoDaysAgo.setDate(twoDaysAgo.getDate() - 2);

    if (eventDate >= twoDaysAgo) {
      const dayKey = eventDate.toISOString().split('T')[0];
      if (!eventsByDay[dayKey]) {
        eventsByDay[dayKey] = [];
      }
      eventsByDay[dayKey].push(event);
    }
  });

  return eventsByDay;
}

export function sortEventsByDateTime(events: Event[]): Event[] {
  return events.sort((a, b) => {
    return new Date(`${a.day}T${a.hora}`).getTime() - new Date(`${b.day}T${b.hora}`).getTime();
  });
}

export function capitalizeFirstLetter(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

export function formatDayName(date: Date): string {
  const dayName = date.toLocaleDateString('es-ES', {
    weekday: 'long',
    day: 'numeric',
    month: 'long',
    year: 'numeric'
  });
  return capitalizeFirstLetter(dayName);
}

export function getBrowserInfo() {
  const ua = navigator.userAgent || navigator.vendor || (window as any).opera;
  const isInstagram = ua.indexOf("Instagram") > -1;
  const isFacebook = (ua.indexOf("FBAN") > -1) || (ua.indexOf("FBAV") > -1);
  const isAndroid = /Android/i.test(ua);
  const isiOS = /iPhone|iPad|iPod/i.test(ua);
  
  return {
    isEmbedded: isInstagram || isFacebook,
    isInstagram,
    isFacebook,
    isAndroid,
    isiOS
  };
}

export function isEmbeddedBrowser(): boolean {
  return getBrowserInfo().isEmbedded;
}

export interface DailyGif {
  emoji: string;
  title: string;
  gifUrl?: string;
}

const giphyGifs = [
  'https://media.giphy.com/media/3o6gDPXMNxFhvHdcf6/giphy.gif',
  'https://media.giphy.com/media/3o6ozvv0zsJskzOCbu/giphy.gif',
  'https://media.giphy.com/media/3o7btPCcdNniyf0ArS/giphy.gif',
  'https://media.giphy.com/media/3o7TKMt1VVNkHV2PaE/giphy.gif',
  'https://media.giphy.com/media/3oriO0OEd9QIDdllqo/giphy.gif',
  'https://media.giphy.com/media/l0HlvtIPzPdt2usKs/giphy.gif',
  'https://media.giphy.com/media/l0Iyl55kTeh71nTXy/giphy.gif',
  'https://media.giphy.com/media/l0MYGb1LuZ3n7dRnO/giphy.gif',
  'https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif',
  'https://media.giphy.com/media/l3fQf1OEAq0iri9RC/giphy.gif',
  'https://media.giphy.com/media/l41YtZOb9EUABnuqA/giphy.gif',
  'https://media.giphy.com/media/EiTLChyoHWAHdqHdCG/giphy.gif',
  'https://media.giphy.com/media/gUv5wlJy3p6ZEPFdCe/giphy.gif',
  'https://media.giphy.com/media/5VPIhpelC46f66sgEQ/giphy.gif',
  'https://media.giphy.com/media/o941WY0z2YT84OisLY/giphy.gif',
  'https://media.giphy.com/media/12k4CELogBv4l2/giphy.gif',
  'https://media.giphy.com/media/i7KXXykHSyaX6h17iF/giphy.gif',
  'https://media.giphy.com/media/ZtMkorgeyRu5q/giphy.gif',
  'https://media.giphy.com/media/KeS67OjA8JSQU/giphy.gif',
  'https://media.giphy.com/media/Bl10664xbIVkk/giphy.gif',
  'https://media.giphy.com/media/7TM8kWy04HzcA/giphy.gif',
  'https://media.giphy.com/media/3o6gDPXMNxFhvHdcf6/giphy.gif',
  'https://media.giphy.com/media/3o6ozvv0zsJskzOCbu/giphy.gif',
  'https://media.giphy.com/media/3o7btPCcdNniyf0ArS/giphy.gif',
  'https://media.giphy.com/media/3o7TKMt1VVNkHV2PaE/giphy.gif',
  'https://media.giphy.com/media/3oriO0OEd9QIDdllqo/giphy.gif',
  'https://media.giphy.com/media/l0HlvtIPzPdt2usKs/giphy.gif',
  'https://media.giphy.com/media/l0Iyl55kTeh71nTXy/giphy.gif',
  'https://media.giphy.com/media/l0MYGb1LuZ3n7dRnO/giphy.gif',
  'https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif',
  'https://media.giphy.com/media/l3fQf1OEAq0iri9RC/giphy.gif',
  'https://media.giphy.com/media/l41YtZOb9EUABnuqA/giphy.gif',
  'https://media.giphy.com/media/EiTLChyoHWAHdqHdCG/giphy.gif',
  'https://media.giphy.com/media/gUv5wlJy3p6ZEPFdCe/giphy.gif',
  'https://media.giphy.com/media/5VPIhpelC46f66sgEQ/giphy.gif',
  'https://media.giphy.com/media/o941WY0z2YT84OisLY/giphy.gif',
  'https://media.giphy.com/media/12k4CELogBv4l2/giphy.gif',
  'https://media.giphy.com/media/i7KXXykHSyaX6h17iF/giphy.gif',
  'https://media.giphy.com/media/ZtMkorgeyRu5q/giphy.gif',
  'https://media.giphy.com/media/KeS67OjA8JSQU/giphy.gif',
  'https://media.giphy.com/media/Bl10664xbIVkk/giphy.gif',
  'https://media.giphy.com/media/7TM8kWy04HzcA/giphy.gif',
  'https://media.giphy.com/media/3o6gDPXMNxFhvHdcf6/giphy.gif',
  'https://media.giphy.com/media/3o6ozvv0zsJskzOCbu/giphy.gif',
  'https://media.giphy.com/media/3o7btPCcdNniyf0ArS/giphy.gif',
  'https://media.giphy.com/media/3o7TKMt1VVNkHV2PaE/giphy.gif',
  'https://media.giphy.com/media/3oriO0OEd9QIDdllqo/giphy.gif',
  'https://media.giphy.com/media/l0HlvtIPzPdt2usKs/giphy.gif',
  'https://media.giphy.com/media/l0Iyl55kTeh71nTXy/giphy.gif',
  'https://media.giphy.com/media/l0MYGb1LuZ3n7dRnO/giphy.gif',
  'https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif',
  'https://media.giphy.com/media/l3fQf1OEAq0iri9RC/giphy.gif',
  'https://media.giphy.com/media/l41YtZOb9EUABnuqA/giphy.gif',
  'https://media.giphy.com/media/EiTLChyoHWAHdqHdCG/giphy.gif',
  'https://media.giphy.com/media/gUv5wlJy3p6ZEPFdCe/giphy.gif',
  'https://media.giphy.com/media/5VPIhpelC46f66sgEQ/giphy.gif',
  'https://media.giphy.com/media/o941WY0z2YT84OisLY/giphy.gif',
  'https://media.giphy.com/media/12k4CELogBv4l2/giphy.gif',
  'https://media.giphy.com/media/i7KXXykHSyaX6h17iF/giphy.gif',
  'https://media.giphy.com/media/ZtMkorgeyRu5q/giphy.gif',
  'https://media.giphy.com/media/KeS67OjA8JSQU/giphy.gif',
  'https://media.giphy.com/media/Bl10664xbIVkk/giphy.gif',
  'https://media.giphy.com/media/7TM8kWy04HzcA/giphy.gif',
  'https://media.giphy.com/media/3o6gDPXMNxFhvHdcf6/giphy.gif',
  'https://media.giphy.com/media/3o6ozvv0zsJskzOCbu/giphy.gif',
  'https://media.giphy.com/media/3o7btPCcdNniyf0ArS/giphy.gif',
  'https://media.giphy.com/media/3o7TKMt1VVNkHV2PaE/giphy.gif',
  'https://media.giphy.com/media/3oriO0OEd9QIDdllqo/giphy.gif',
  'https://media.giphy.com/media/l0HlvtIPzPdt2usKs/giphy.gif',
  'https://media.giphy.com/media/l0Iyl55kTeh71nTXy/giphy.gif',
  'https://media.giphy.com/media/l0MYGb1LuZ3n7dRnO/giphy.gif',
  'https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif',
  'https://media.giphy.com/media/l3fQf1OEAq0iri9RC/giphy.gif',
  'https://media.giphy.com/media/l41YtZOb9EUABnuqA/giphy.gif',
  'https://media.giphy.com/media/EiTLChyoHWAHdqHdCG/giphy.gif',
  'https://media.giphy.com/media/gUv5wlJy3p6ZEPFdCe/giphy.gif',
  'https://media.giphy.com/media/5VPIhpelC46f66sgEQ/giphy.gif',
  'https://media.giphy.com/media/o941WY0z2YT84OisLY/giphy.gif',
  'https://media.giphy.com/media/12k4CELogBv4l2/giphy.gif',
  'https://media.giphy.com/media/i7KXXykHSyaX6h17iF/giphy.gif',
  'https://media.giphy.com/media/ZtMkorgeyRu5q/giphy.gif',
  'https://media.giphy.com/media/KeS67OjA8JSQU/giphy.gif',
  'https://media.giphy.com/media/Bl10664xbIVkk/giphy.gif',
  'https://media.giphy.com/media/7TM8kWy04HzcA/giphy.gif',
  'https://media.giphy.com/media/3o6gDPXMNxFhvHdcf6/giphy.gif',
  'https://media.giphy.com/media/3o6ozvv0zsJskzOCbu/giphy.gif',
  'https://media.giphy.com/media/3o7btPCcdNniyf0ArS/giphy.gif',
  'https://media.giphy.com/media/3o7TKMt1VVNkHV2PaE/giphy.gif',
  'https://media.giphy.com/media/3oriO0OEd9QIDdllqo/giphy.gif',
  'https://media.giphy.com/media/l0HlvtIPzPdt2usKs/giphy.gif',
  'https://media.giphy.com/media/l0Iyl55kTeh71nTXy/giphy.gif',
  'https://media.giphy.com/media/l0MYGb1LuZ3n7dRnO/giphy.gif',
  'https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif',
  'https://media.giphy.com/media/l3fQf1OEAq0iri9RC/giphy.gif',
  'https://media.giphy.com/media/l41YtZOb9EUABnuqA/giphy.gif',
  'https://media.giphy.com/media/EiTLChyoHWAHdqHdCG/giphy.gif',
  'https://media.giphy.com/media/gUv5wlJy3p6ZEPFdCe/giphy.gif',
  'https://media.giphy.com/media/5VPIhpelC46f66sgEQ/giphy.gif',
  'https://media.giphy.com/media/o941WY0z2YT84OisLY/giphy.gif',
  'https://media.giphy.com/media/12k4CELogBv4l2/giphy.gif',
  'https://media.giphy.com/media/i7KXXykHSyaX6h17iF/giphy.gif',
  'https://media.giphy.com/media/ZtMkorgeyRu5q/giphy.gif',
  'https://media.giphy.com/media/KeS67OjA8JSQU/giphy.gif',
  'https://media.giphy.com/media/Bl10664xbIVkk/giphy.gif',
  'https://media.giphy.com/media/7TM8kWy04HzcA/giphy.gif',
  'https://media.giphy.com/media/3o6gDPXMNxFhvHdcf6/giphy.gif',
  'https://media.giphy.com/media/3o6ozvv0zsJskzOCbu/giphy.gif',
  'https://media.giphy.com/media/3o7btPCcdNniyf0ArS/giphy.gif',
  'https://media.giphy.com/media/3o7TKMt1VVNkHV2PaE/giphy.gif',
  'https://media.giphy.com/media/3oriO0OEd9QIDdllqo/giphy.gif',
  'https://media.giphy.com/media/l0HlvtIPzPdt2usKs/giphy.gif',
  'https://media.giphy.com/media/l0Iyl55kTeh71nTXy/giphy.gif',
  'https://media.giphy.com/media/l0MYGb1LuZ3n7dRnO/giphy.gif',
  'https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif',
  'https://media.giphy.com/media/l3fQf1OEAq0iri9RC/giphy.gif',
  'https://media.giphy.com/media/l41YtZOb9EUABnuqA/giphy.gif',
  'https://media.giphy.com/media/EiTLChyoHWAHdqHdCG/giphy.gif',
  'https://media.giphy.com/media/gUv5wlJy3p6ZEPFdCe/giphy.gif',
  'https://media.giphy.com/media/5VPIhpelC46f66sgEQ/giphy.gif',
  'https://media.giphy.com/media/o941WY0z2YT84OisLY/giphy.gif',
  'https://media.giphy.com/media/12k4CELogBv4l2/giphy.gif',
  'https://media.giphy.com/media/i7KXXykHSyaX6h17iF/giphy.gif',
  'https://media.giphy.com/media/ZtMkorgeyRu5q/giphy.gif',
  'https://media.giphy.com/media/KeS67OjA8JSQU/giphy.gif',
  'https://media.giphy.com/media/Bl10664xbIVkk/giphy.gif',
  'https://media.giphy.com/media/7TM8kWy04HzcA/giphy.gif',
  'https://media.giphy.com/media/3o6gDPXMNxFhvHdcf6/giphy.gif',
  'https://media.giphy.com/media/3o6ozvv0zsJskzOCbu/giphy.gif',
  'https://media.giphy.com/media/3o7btPCcdNniyf0ArS/giphy.gif',
  'https://media.giphy.com/media/3o7TKMt1VVNkHV2PaE/giphy.gif',
  'https://media.giphy.com/media/3oriO0OEd9QIDdllqo/giphy.gif',
  'https://media.giphy.com/media/l0HlvtIPzPdt2usKs/giphy.gif',
  'https://media.giphy.com/media/l0Iyl55kTeh71nTXy/giphy.gif',
  'https://media.giphy.com/media/l0MYGb1LuZ3n7dRnO/giphy.gif',
  'https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif',
  'https://media.giphy.com/media/l3fQf1OEAq0iri9RC/giphy.gif',
  'https://media.giphy.com/media/l41YtZOb9EUABnuqA/giphy.gif',
  'https://media.giphy.com/media/EiTLChyoHWAHdqHdCG/giphy.gif',
  'https://media.giphy.com/media/gUv5wlJy3p6ZEPFdCe/giphy.gif',
  'https://media.giphy.com/media/5VPIhpelC46f66sgEQ/giphy.gif',
  'https://media.giphy.com/media/o941WY0z2YT84OisLY/giphy.gif',
  'https://media.giphy.com/media/12k4CELogBv4l2/giphy.gif',
  'https://media.giphy.com/media/i7KXXykHSyaX6h17iF/giphy.gif',
  'https://media.giphy.com/media/ZtMkorgeyRu5q/giphy.gif',
  'https://media.giphy.com/media/KeS67OjA8JSQU/giphy.gif',
  'https://media.giphy.com/media/Bl10664xbIVkk/giphy.gif',
  'https://media.giphy.com/media/7TM8kWy04HzcA/giphy.gif',
];

export function getRandomGif(): DailyGif {
  const randomIndex = Math.floor(Math.random() * giphyGifs.length);
  return {
    emoji: '🎉',
    title: 'Gif divertido',
    gifUrl: giphyGifs[randomIndex],
  };
}

const defaultEmojis = [
  { emoji: '🎉', title: '¡Nueva Jahr!' },
  { emoji: '💃', title: '¡A bailar!' },
  { emoji: '🎵', title: 'Música' },
  { emoji: '🎸', title: 'Guitarra' },
  { emoji: '🥁', title: 'Batería' },
  { emoji: '🎺', title: 'Trompeta' },
  { emoji: '🎹', title: 'Teclado' },
  { emoji: '🪘', title: 'Percusión' },
  { emoji: '🎤', title: 'Micrófono' },
  { emoji: '🎧', title: 'DJ' },
  { emoji: '🕺', title: 'Baile' },
  { emoji: '💫', title: 'Estrellas' },
  { emoji: '✨', title: 'Brillo' },
  { emoji: '🌟', title: 'Estrella' },
  { emoji: '🔥', title: 'Fuego' },
  { emoji: '💥', title: 'Explosión' },
  { emoji: '⚡', title: 'Energía' },
  { emoji: '🎆', title: 'Fuegos' },
  { emoji: '🎇', title: 'Regalo' },
  { emoji: '🥳', title: 'Fiesta' },
];

export function getRandomEmoji(): DailyGif {
  const randomIndex = Math.floor(Math.random() * defaultEmojis.length);
  return defaultEmojis[randomIndex];
}

const dailyGifs: DailyGif[] = [
  { emoji: '🎉', title: '¡Nueva Jahr!' },
  { emoji: '💃', title: '¡A bailar!' },
  { emoji: '🎵', title: 'Música' },
  { emoji: '🎸', title: 'Guitarra' },
  { emoji: '🥁', title: 'Batería' },
  { emoji: '🎺', title: 'Trompeta' },
  { emoji: '🎹', title: 'Teclado' },
  { emoji: '🪘', title: 'Percusión' },
  { emoji: '🎤', title: 'Micrófono' },
  { emoji: '🎧', title: 'DJ' },
  { emoji: '🕺', title: 'Baile' },
  { emoji: '💫', title: 'Estrellas' },
  { emoji: '✨', title: 'Brillo' },
  { emoji: '🌟', title: 'Estrella' },
  { emoji: '🔥', title: 'Fuego' },
  { emoji: '💥', title: 'Explosión' },
  { emoji: '⚡', title: 'Energía' },
  { emoji: '🎆', title: 'Fuegos' },
  { emoji: '🎇', title: 'Regalo' },
  { emoji: '🥳', title: 'Fiesta' },
  { emoji: '😎', title: '¡Qué pasada!' },
  { emoji: '🤩', title: '¡Increíble!' },
  { emoji: '🎊', title: 'Confeti' },
  { emoji: '🎋', title: 'Celebración' },
  { emoji: '🎭', title: 'Máscara' },
  { emoji: '🎪', title: 'Circo' },
  { emoji: '🎡', title: 'Noria' },
  { emoji: '🎠', title: 'Caballo' },
  { emoji: '🎢', title: 'Montaña' },
  { emoji: '🏃', title: '¡Corre!' },
  { emoji: '🌀', title: 'Giro' },
  { emoji: '💃', title: 'Sevillanas' },
  { emoji: '🪕', title: 'Timple' },
  { emoji: '🌺', title: 'Flama' },
  { emoji: '🦎', title: 'Lagarto' },
  { emoji: '🌴', title: 'Palmera' },
  { emoji: '🏝️', title: 'Isla' },
  { emoji: '🌊', title: 'Olas' },
  { emoji: '☀️', title: 'Sol' },
  { emoji: '🌅', title: 'Atardecer' },
  { emoji: '🌇', title: 'Puesta sol' },
  { emoji: '🏖️', title: 'Playa' },
  { emoji: '🏜️', title: 'Desierto' },
  { emoji: '⛰️', title: 'Montaña' },
  { emoji: '🏔️', title: 'Pico' },
  { emoji: '🌋', title: 'Volcán' },
  { emoji: '🌵', title: 'Cactus' },
  { emoji: '🌺', title: 'Hibisco' },
  { emoji: '🌸', title: 'Flor' },
  { emoji: '🌻', title: 'Girasol' },
  { emoji: '🌹', title: 'Rosa' },
  { emoji: '🌷', title: 'Tulipán' },
  { emoji: '🍀', title: 'Trébol' },
  { emoji: '🍁', title: 'Hoja' },
  { emoji: '🍃', title: 'Hojas' },
  { emoji: '🌿', title: 'Planta' },
  { emoji: '🎋', title: 'Bambú' },
  { emoji: '🍄', title: 'Champiñón' },
  { emoji: '🌰', title: 'Castaña' },
  { emoji: '🥥', title: 'Coco' },
  { emoji: '🍍', title: 'Piña' },
  { emoji: '🥭', title: 'Mango' },
  { emoji: '🍌', title: 'Plátano' },
  { emoji: '🍉', title: 'Sandía' },
  { emoji: '🍇', title: 'Uvas' },
  { emoji: '🍈', title: 'Melón' },
  { emoji: '🍒', title: 'Cerezas' },
  { emoji: '🍓', title: 'Fresa' },
  { emoji: '🫐', title: 'Arándano' },
  { emoji: '🥝', title: 'Kiwi' },
  { emoji: '🍊', title: 'Naranja' },
  { emoji: '🍋', title: 'Limón' },
  { emoji: '🍏', title: 'Manzana' },
  { emoji: '🍐', title: 'Pera' },
  { emoji: '🥑', title: 'Aguacate' },
  { emoji: '🍅', title: 'Tomate' },
  { emoji: '🥒', title: 'Pepino' },
  { emoji: '🌶️', title: 'Pimiento' },
  { emoji: '🌽', title: 'Maíz' },
  { emoji: '🥕', title: 'Zanahoria' },
  { emoji: '🥦', title: 'Brócoli' },
  { emoji: '🧅', title: 'Cebolla' },
  { emoji: '🧄', title: 'Ajo' },
  { emoji: '🥔', title: 'Patata' },
  { emoji: '🍞', title: 'Pan' },
  { emoji: '🥖', title: 'Baguette' },
  { emoji: '🥨', title: 'Pretzel' },
  { emoji: '🥐', title: 'Croissant' },
  { emoji: '🥯', title: 'Bagel' },
  { emoji: '🥞', title: 'Crepes' },
  { emoji: '🧇', title: 'Gofre' },
  { emoji: '🧀', title: 'Queso' },
  { emoji: '🥚', title: 'Huevo' },
  { emoji: '🍳', title: 'Huevos' },
  { emoji: '🥓', title: 'Tocino' },
  { emoji: '🥞', title: 'Tortitas' },
  { emoji: '🧈', title: 'Mantequilla' },
  { emoji: '🍯', title: 'Miel' },
  { emoji: '🥣', title: 'Cereal' },
  { emoji: '🥗', title: 'Ensalada' },
  { emoji: '🍝', title: 'Pasta' },
  { emoji: '🍣', title: 'Sushi' },
  { emoji: '🍱', title: 'Bento' },
  { emoji: '🥟', title: 'Dumplings' },
  { emoji: '🍜', title: 'Fideos' },
  { emoji: '🍲', title: 'Cazuela' },
  { emoji: '🥘', title: 'Paella' },
  { emoji: '🍛', title: 'Curry' },
  { emoji: '🍢', title: 'Takoyaki' },
  { emoji: '🍤', title: 'Tempura' },
  { emoji: '🍟', title: 'Patatas' },
  { emoji: '🍕', title: 'Pizza' },
  { emoji: '🌮', title: 'Taco' },
  { emoji: '🌯', title: 'Burrito' },
  { emoji: '🥙', title: 'Kebab' },
  { emoji: '🥗', title: 'Wrap' },
  { emoji: '🥫', title: 'Estofado' },
  { emoji: '🍝', title: 'Espagueti' },
  { emoji: '🍝', title: 'Lasaña' },
  { emoji: '🥧', title: 'Pastel' },
  { emoji: '🧁', title: 'Cupcake' },
  { emoji: '🍰', title: 'Tarta' },
  { emoji: '🎂', title: 'Cumpleaños' },
  { emoji: '🍪', title: 'Galleta' },
  { emoji: '🍩', title: 'Donut' },
  { emoji: '🍫', title: 'Chocolate' },
  { emoji: '🍬', title: 'Caramelo' },
  { emoji: '🍭', title: 'Chupete' },
  { emoji: '🍡', title: 'Dango' },
  { emoji: '🍮', title: 'Flan' },
  { emoji: '🍦', title: 'Helado' },
  { emoji: '🍨', title: 'Sorbete' },
  { emoji: '🥤', title: 'Refresco' },
  { emoji: '🧃', title: 'Zumo' },
  { emoji: '🍵', title: 'Té' },
  { emoji: '☕', title: 'Café' },
  { emoji: '🍺', title: 'Cerveza' },
  { emoji: '🍻', title: 'Chin chin' },
  { emoji: '🥂', title: 'Champán' },
  { emoji: '🍷', title: 'Vino' },
  { emoji: '🍹', title: 'Cóctel' },
  { emoji: '🍸', title: 'Cóctel fino' },
  { emoji: '🍾', title: 'Botella' },
  { emoji: '🥃', title: 'Whisky' },
  { emoji: '🧉', title: 'Margarita' },
  { emoji: '🧋', title: 'Boba' },
  { emoji: '🧃', title: 'Batido' },
  { emoji: '🍪', title: 'Galleta' },
  { emoji: '🥜', title: 'Cacahuetes' },
  { emoji: '🥨', title: 'Pistachos' },
  { emoji: '🍿', title: 'Palomitas' },
  { emoji: '🥚', title: 'Huevos' },
  { emoji: '🍗', title: 'Pollo' },
  { emoji: '🍖', title: 'Carne' },
  { emoji: '🥩', title: 'Filete' },
  { emoji: '🍔', title: 'Hamburguesa' },
  { emoji: '🌭', title: 'Perrito' },
  { emoji: '🥪', title: 'Sándwich' },
  { emoji: '🥙', title: 'Pan pita' },
  { emoji: '🍙', title: 'Onigiri' },
  { emoji: '🍘', title: 'Crackers' },
  { emoji: '🍥', title: 'Fish cake' },
  { emoji: '🥠', title: 'Galleta suerte' },
  { emoji: '🥡', title: 'Takeout' },
  { emoji: '🥢', title: 'Palillos' },
  { emoji: '🍽️', title: 'Platos' },
  { emoji: '🍴', title: 'Cubiertos' },
  { emoji: '🥄', title: 'Cuchara' },
  { emoji: '🍾', title: '¡Salud!' },
  { emoji: '🌮', title: '¡Provecho!' },
  { emoji: '🍕', title: '¡Delicioso!' },
  { emoji: '🍟', title: 'Crujiente' },
  { emoji: '🌭', title: '¡Jugoso!' },
  { emoji: '🏠', title: 'Casa' },
  { emoji: '🏡', title: 'Jardín' },
  { emoji: '🏢', title: 'Edificio' },
  { emoji: '🏰', title: 'Castillo' },
  { emoji: '⛪', title: 'Iglesia' },
  { emoji: '🕌', title: 'Mezquita' },
  { emoji: '🛕', title: 'Templo' },
  { emoji: '⛩️', title: 'Santuario' },
  { emoji: '🏛️', title: 'Museo' },
  { emoji: '🏟️', title: 'Estadio' },
  { emoji: '🎪', title: 'Carpa' },
  { emoji: '🎭', title: 'Teatro' },
  { emoji: '🎨', title: 'Arte' },
  { emoji: '🎬', title: 'Cine' },
  { emoji: '📺', title: 'TV' },
  { emoji: '📻', title: 'Radio' },
  { emoji: '🎧', title: 'Auriculares' },
  { emoji: '📱', title: 'Móvil' },
  { emoji: '💻', title: 'Ordenador' },
  { emoji: '⌨️', title: 'Teclado' },
  { emoji: '🖱️', title: 'Ratón' },
  { emoji: '💾', title: 'Disquete' },
  { emoji: '💿', title: 'CD' },
  { emoji: '📀', title: 'DVD' },
  { emoji: '🎮', title: 'Consola' },
  { emoji: '🎲', title: 'Dados' },
  { emoji: '♟️', title: 'Ajedrez' },
  { emoji: '🎯', title: 'Dardos' },
  { emoji: '🏀', title: 'Baloncesto' },
  { emoji: '⚽', title: 'Fútbol' },
  { emoji: '⚾', title: 'Béisbol' },
  { emoji: '🥎', title: 'Softbol' },
  { emoji: '🎾', title: 'Tenis' },
  { emoji: '🏐', title: 'Voleibol' },
  { emoji: '🏉', title: 'Rugby' },
  { emoji: '🥏', title: 'Ultimate' },
  { emoji: '🎱', title: 'Billar' },
  { emoji: '🏓', title: 'Ping pong' },
  { emoji: '🏸', title: 'Bádminton' },
  { emoji: '🥊', title: 'Boxeo' },
  { emoji: '🥋', title: 'Karate' },
  { emoji: '🤸', title: 'Gimnasia' },
  { emoji: '🤾', title: 'Balonmano' },
  { emoji: '🏎️', title: 'Coche' },
  { emoji: '🏎️', title: 'Carrera' },
  { emoji: '🚦', title: 'Semáforo' },
  { emoji: '✈️', title: 'Avión' },
  { emoji: '🚀', title: 'Cohete' },
  { emoji: '🛸', title: 'OVNI' },
  { emoji: '🚁', title: 'Helicóptero' },
  { emoji: '⛵', title: 'Barco' },
  { emoji: '🛳️', title: 'Crucero' },
  { emoji: '🚂', title: 'Tren' },
  { emoji: '🚃', title: 'Metro' },
  { emoji: '🚗', title: 'Coche' },
  { emoji: '🚕', title: 'Taxi' },
  { emoji: '🚌', title: 'Autobús' },
  { emoji: '🚑', title: 'Ambulancia' },
  { emoji: '🚒', title: 'Bomberos' },
  { emoji: '🚓', title: 'Policía' },
  { emoji: '🚜', title: 'Tractor' },
  { emoji: '🚲', title: 'Bicicleta' },
  { emoji: '🛴', title: 'Patinete' },
  { emoji: '🛹', title: 'Skate' },
  { emoji: '🏄', title: 'Surf' },
  { emoji: '🏊', title: 'Natación' },
  { emoji: '🤿', title: 'Buceo' },
  { emoji: '🚣', title: 'Piragua' },
  { emoji: '🧗', title: 'Escalada' },
  { emoji: '🏔️', title: 'Alpinismo' },
  { emoji: '🏇', title: 'Caballo' },
  { emoji: '🧘', title: 'Yoga' },
  { emoji: '🏋️', title: 'Gimnasio' },
  { emoji: '🚴', title: 'Ciclismo' },
  { emoji: '🚵', title: 'MTB' },
  { emoji: '⛷️', title: 'Esquí' },
  { emoji: '🏂', title: 'Snowboard' },
  { emoji: '🛷', title: 'Trineo' },
  { emoji: '⛸️', title: 'Patinaje' },
  { emoji: '🏒', title: 'Hockey' },
  { emoji: '🏑', title: 'Lacrosse' },
  { emoji: '🥍', title: 'Squash' },
  { emoji: '🏏', title: 'Críquet' },
  { emoji: '🪃', title: 'Bumerán' },
  { emoji: '🪁', title: 'Cometa' },
  { emoji: '🎣', title: 'Pescar' },
  { emoji: '🤿', title: 'Snorkel' },
  { emoji: '🏟️', title: 'Estadio' },
  { emoji: '🎪', title: 'Circo' },
  { emoji: '🎡', title: 'Noria' },
  { emoji: '🎢', title: 'Montaña' },
  { emoji: '🎠', title: 'Carrusel' },
  { emoji: '🎬', title: 'Rodaje' },
  { emoji: '🎙️', title: 'Directo' },
  { emoji: '🎚️', title: 'Mezclador' },
  { emoji: '🎛️', title: 'Mesa sonido' },
  { emoji: '🎝️', title: 'Piano' },
  { emoji: '🎖️', title: 'Medalla' },
  { emoji: '🏆', title: 'Trofeo' },
  { emoji: '🥇', title: 'Oro' },
  { emoji: '🥈', title: 'Plata' },
  { emoji: '🥉', title: 'Bronce' },
  { emoji: '👑', title: 'Corona' },
  { emoji: '💎', title: 'Diamante' },
  { emoji: '💍', title: 'Anillo' },
  { emoji: '💐', title: 'Ramo' },
  { emoji: '💌', title: 'Carta' },
  { emoji: '💌', title: 'Amor' },
  { emoji: '❤️', title: 'Corazón' },
  { emoji: '💕', title: 'Corazones' },
  { emoji: '💖', title: 'Brillo corazón' },
  { emoji: '💗', title: 'Latido' },
  { emoji: '💓', title: 'Pulso' },
  { emoji: '💞', title: 'Girando' },
  { emoji: '💟', title: 'Corazón decorative' },
  { emoji: '❣️', title: 'Corazón exclamación' },
  { emoji: '💔', title: 'Corazón roto' },
  { emoji: '🧡', title: 'Naranja' },
  { emoji: '💛', title: 'Amarillo' },
  { emoji: '💚', title: 'Verde' },
  { emoji: '💙', title: 'Azul' },
  { emoji: '💜', title: 'Morado' },
  { emoji: '🖤', title: 'Negro' },
  { emoji: '🤍', title: 'Blanco' },
  { emoji: '🤎', title: 'Marrón' },
  { emoji: '💯', title: '100' },
  { emoji: '💯', title: 'Perfecto' },
  { emoji: '✅', title: 'OK' },
  { emoji: '🎉', title: '¡Felicidades!' },
  { emoji: '🎊', title: '¡Enhorabuena!' },
  { emoji: '🥳', title: '¡A celebrar!' },
  { emoji: '🤩', title: '¡Genial!' },
  { emoji: '😎', title: '¡Cool!' },
  { emoji: '🔥', title: '¡Qué fuerte!' },
  { emoji: '💪', title: '¡Tú puedes!' },
  { emoji: '🚀', title: '¡Despega!' },
  { emoji: '⭐', title: 'Estrella' },
  { emoji: '🌟', title: 'Brilla' },
  { emoji: '✨', title: 'Magia' },
  { emoji: '💫', title: 'Sueños' },
  { emoji: '💥', title: 'Boom' },
  { emoji: '💢', title: 'Enfado' },
  { emoji: '💦', title: 'Splash' },
  { emoji: '💨', title: 'Velocidad' },
  { emoji: '🕳️', title: 'Agujero' },
  { emoji: '💬', title: 'Charla' },
  { emoji: '💭', title: 'Pensando' },
  { emoji: '💤', title: 'Sueño' },
  { emoji: '💤', title: 'Zzz' },
  { emoji: '👋', title: 'Hola' },
  { emoji: '🤚', title: 'Saludo' },
  { emoji: '🖐️', title: 'Mano' },
  { emoji: '✋', title: 'Alto' },
  { emoji: '🖖', title: 'Vulcano' },
  { emoji: '👌', title: 'OK' },
  { emoji: '🤌', title: 'Italian' },
  { emoji: '🤏', title: 'Poco' },
  { emoji: '✌️', title: 'Paz' },
  { emoji: '🤞', title: 'Suerte' },
  { emoji: '🤟', title: 'Amor' },
  { emoji: '🤘', title: 'Rock' },
  { emoji: '🤙', title: 'Aloha' },
  { emoji: '👈', title: 'Apuntar' },
  { emoji: '👉', title: 'Aqui' },
  { emoji: '👆', title: 'Arriba' },
  { emoji: '👇', title: 'Abajo' },
  { emoji: '☝️', title: 'Uno' },
  { emoji: '👍', title: 'Like' },
  { emoji: '👎', title: 'Dislike' },
  { emoji: '👏', title: 'Clap' },
  { emoji: '🙌', title: 'Yay' },
  { emoji: '🤝', title: 'Pacto' },
  { emoji: '🙏', title: 'Gracias' },
  { emoji: '👐', title: 'Abrazo' },
  { emoji: '🤲', title: 'Palmas' },
  { emoji: '🫶', title: 'Corazón manos' },
  { emoji: '🤝', title: 'Manos' },
  { emoji: '💅', title: 'Uñas' },
  { emoji: '🤳', title: 'Selfie' },
  { emoji: '💪', title: 'Fuerza' },
  { emoji: '🦾', title: 'Brazo robótico' },
  { emoji: '🦿', title: 'Pierna' },
  { emoji: '🦵', title: 'Pierna' },
  { emoji: '🦶', title: 'Pie' },
  { emoji: '👂', title: 'Oreja' },
  { emoji: '👃', title: 'Nariz' },
  { emoji: '🧠', title: 'Cerebro' },
  { emoji: '🦷', title: 'Diente' },
  { emoji: '👀', title: 'Ojos' },
  { emoji: '👁️', title: 'Ojo' },
  { emoji: '👅', title: 'Lengua' },
  { emoji: '👄', title: 'Labios' },
  { emoji: '👶', title: 'Bebé' },
  { emoji: '🧒', title: 'Niño' },
  { emoji: '👦', title: 'Chico' },
  { emoji: '👧', title: 'Chica' },
  { emoji: '🧑', title: 'Adulto' },
  { emoji: '👱', title: 'Rubio' },
  { emoji: '👨', title: 'Hombre' },
  { emoji: '🧔', title: 'Barba' },
  { emoji: '👩', title: 'Mujer' },
  { emoji: '🧓', title: 'Anciano' },
  { emoji: '👴', title: 'Abuelo' },
  { emoji: '👵', title: 'Abuela' },
  { emoji: '🙇', title: 'Reverencia' },
  { emoji: '💁', title: 'Información' },
  { emoji: '🙆', title: 'Gestos' },
  { emoji: '🙋', title: 'Levantar mano' },
  { emoji: '🧏', title: 'Sordo' },
  { emoji: '🙍', title: 'Triste' },
  { emoji: '🙎', title: 'Enfadado' },
  { emoji: '🙈', title: 'No ver' },
  { emoji: '🙉', title: 'No oír' },
  { emoji: '🙊', title: 'No hablar' },
  { emoji: '💂', title: 'Guardia' },
  { emoji: '🕵️', title: 'Detective' },
  { emoji: '👮', title: 'Policía' },
  { emoji: '🧑‍⚕️', title: 'Doctor' },
  { emoji: '🧑‍🏫', title: 'Profesor' },
  { emoji: '🧑‍🍳', title: 'Cocinero' },
  { emoji: '🧑‍🌾', title: 'Granjero' },
  { emoji: '🧑‍🏭', title: 'Obrero' },
  { emoji: '🧑‍💻', title: 'Tech' },
  { emoji: '🧑‍🎨', title: 'Artista' },
  { emoji: '🧑‍🎤', title: 'Cantor' },
  { emoji: '🧑‍🏀', title: 'Deportista' },
  { emoji: '🧑‍🚀', title: 'Astronauta' },
  { emoji: '🧑‍🔬', title: 'Científico' },
  { emoji: '🐶', title: 'Perro' },
  { emoji: '🐱', title: 'Gato' },
  { emoji: '🐭', title: 'Ratón' },
  { emoji: '🐹', title: 'Hámster' },
  { emoji: '🐰', title: 'Conejo' },
  { emoji: '🦊', title: 'Zorro' },
  { emoji: '🐻', title: 'Oso' },
  { emoji: '🐼', title: 'Panda' },
  { emoji: '🐨', title: 'Koala' },
  { emoji: '🐯', title: 'Tigre' },
  { emoji: '🦁', title: 'León' },
  { emoji: '🐮', title: 'Vaca' },
  { emoji: '🐷', title: 'Cerdo' },
  { emoji: '🐸', title: 'Rana' },
  { emoji: '🐵', title: 'Mono' },
  { emoji: '🐔', title: 'Gallina' },
  { emoji: '🐧', title: 'Pingüino' },
  { emoji: '🐦', title: 'Pájaro' },
  { emoji: '🦅', title: 'Águila' },
  { emoji: '🦆', title: 'Pato' },
  { emoji: '🦉', title: 'Búho' },
  { emoji: '🦜', title: 'Loro' },
  { emoji: '🐢', title: 'Tortuga' },
  { emoji: '🐍', title: 'Serpiente' },
  { emoji: '🦎', title: 'Lagarto' },
  { emoji: '🦂', title: 'Escorpión' },
  { emoji: '🐛', title: 'Oruga' },
  { emoji: '🦋', title: 'Mariposa' },
  { emoji: '🐝', title: 'Abeja' },
  { emoji: '🐞', title: 'Cucaracha' },
  { emoji: '🦟', title: 'Mosquito' },
  { emoji: '🐌', title: 'Caracol' },
  { emoji: '🐙', title: 'Pulpo' },
  { emoji: '🦑', title: 'Calamar' },
  { emoji: '🦀', title: 'Cangrejo' },
  { emoji: '🐠', title: 'Pez' },
  { emoji: '🐟', title: 'Pez azul' },
  { emoji: '🐡', title: 'Pez globo' },
  { emoji: '🐬', title: 'Delfín' },
  { emoji: '🐳', title: 'Ballena' },
  { emoji: '🦈', title: 'Tiburón' },
  { emoji: '🐊', title: 'Cocodrilo' },
  { emoji: '🐅', title: 'Tigre' },
  { emoji: '🐆', title: 'Leopardo' },
  { emoji: '🦓', title: 'Cebra' },
  { emoji: '🦍', title: 'Gorila' },
  { emoji: '🦧', title: 'Chimpancé' },
  { emoji: '🦣', title: 'Mamut' },
  { emoji: '🦛', title: 'Hipopótamo' },
  { emoji: '🦏', title: 'Rinoceronte' },
  { emoji: '🐘', title: 'Elefante' },
  { emoji: '🦒', title: 'Jirafa' },
  { emoji: '🦘', title: 'Canguro' },
  { emoji: '🦬', title: 'Búfalo' },
  { emoji: '🦙', title: 'Llama' },
  { emoji: '🦙', title: 'Alpaca' },
  { emoji: '🐪', title: 'Dromedario' },
  { emoji: '🐫', title: 'Camello' },
  { emoji: '🦌', title: 'Ciervo' },
  { emoji: '🦝', title: 'Mapache' },
  { emoji: '🦨', title: 'Zorrillo' },
  { emoji: '🦡', title: 'Tejón' },
  { emoji: '🦦', title: 'Nutria' },
  { emoji: '🦥', title: 'Perezoso' },
  { emoji: '🦨', title: 'Mofeta' },
  { emoji: '🐿️', title: 'Ardilla' },
  { emoji: '🐇', title: 'Conejo' },
  { emoji: '🦔', title: 'Erizo' },
  { emoji: '🐁', title: 'Ratón' },
  { emoji: '🐀', title: 'Rata' },
  { emoji: '🐿️', title: 'Chipmunk' },
  { emoji: '🦇', title: 'Murciélago' },
  { emoji: '🐾', title: 'Huellas' },
  { emoji: '🦶', title: 'Huellas pies' },
  { emoji: '🍖', title: 'Hueso' },
  { emoji: '🥚', title: 'Huevo' },
  { emoji: '🐚', title: 'Concha' },
  { emoji: '🌈', title: 'Arcoíris' },
  { emoji: '☀️', title: 'Sol' },
  { emoji: '🌤️', title: 'Parcial' },
  { emoji: '⛅', title: 'Nublado' },
  { emoji: '🌥️', title: 'Nube' },
  { emoji: '🌧️', title: 'Lluvia' },
  { emoji: '⛈️', title: 'Tormenta' },
  { emoji: '🌩️', title: 'Rayos' },
  { emoji: '🌨️', title: 'Nieve' },
  { emoji: '❄️', title: 'Copo' },
  { emoji: '☃️', title: 'Muñeco' },
  { emoji: '🌪️', title: 'Tornado' },
  { emoji: '🌫️', title: 'Niebla' },
  { emoji: '🌬️', title: 'Viento' },
  { emoji: '💨', title: 'Aire' },
  { emoji: '🌊', title: 'Ola' },
  { emoji: '💧', title: 'Gota' },
  { emoji: '💦', title: 'Agua' },
  { emoji: '🫧', title: 'Burbuja' },
  { emoji: '🎈', title: 'Globo' },
  { emoji: '🎉', title: 'Fiesta' },
  { emoji: '🎊', title: 'Confeti' },
  { emoji: '🎁', title: 'Regalo' },
  { emoji: '🎀', title: 'Lazo' },
  { emoji: '🎗️', title: 'Cinta' },
  { emoji: '🎟️', title: 'Entrada' },
  { emoji: '🎫', title: 'Billete' },
  { emoji: '🎭', title: 'Máscaras' },
  { emoji: '🎪', title: 'Carpa' },
  { emoji: '🎨', title: 'Paleta' },
  { emoji: '🎬', title: 'Clapper' },
  { emoji: '🎤', title: 'Mic' },
  { emoji: '🎧', title: 'Auriculares' },
  { emoji: '🎼', title: 'Partitura' },
  { emoji: '🎹', title: 'Teclado' },
  { emoji: '🥁', title: 'Tambor' },
  { emoji: '🎷', title: 'Saxofón' },
  { emoji: '🎺', title: 'Trompeta' },
  { emoji: '🎸', title: 'Guitarra' },
  { emoji: '🪕', title: 'Ukulele' },
  { emoji: '🎻', title: 'Violín' },
  { emoji: '🪈', title: 'Flauta' },
  { emoji: '🎲', title: 'Dados' },
  { emoji: '🎯', title: 'Diana' },
  { emoji: '🎳', title: 'Bolos' },
  { emoji: '🎮', title: 'Mando' },
  { emoji: '🎰', title: 'Slot machine' },
  { emoji: '🃏', title: 'Baraja' },
  { emoji: '🀄', title: 'Mahjong' },
  { emoji: '🎴', title: 'Cartas' },
  { emoji: '🏈', title: 'Fútbol americano' },
  { emoji: '🏉', title: 'Rugby' },
  { emoji: '🎾', title: 'Tenis' },
  { emoji: '🏐', title: 'Voleibol' },
  { emoji: '🏀', title: 'Baloncesto' },
  { emoji: '⚽', title: 'Fútbol' },
  { emoji: '⚾', title: 'Béisbol' },
  { emoji: '🥎', title: 'Softbol' },
  { emoji: '🥏', title: 'Ultimate' },
  { emoji: '🥊', title: 'Boxeo' },
  { emoji: '🥋', title: 'Lucha' },
  { emoji: '🥅', title: 'Gol' },
  { emoji: '⛳', title: 'Golf' },
  { emoji: '🏌️', title: 'Golf swing' },
  { emoji: '🏇', title: 'Caballo' },
  { emoji: '🧗', title: 'Escalar' },
  { emoji: '🚴', title: 'Bici' },
  { emoji: '🏊', title: 'Nadar' },
  { emoji: '🤿', title: 'Submarino' },
  { emoji: '🚣', title: 'Remar' },
  { emoji: '🛀', title: 'Baño' },
  { emoji: '🛌', title: 'Cama' },
  { emoji: '🧘', title: 'Meditar' },
  { emoji: '🚶', title: 'Caminar' },
  { emoji: '🏃', title: 'Correr' },
  { emoji: '🧍', title: 'Pararse' },
  { emoji: '🧎', title: 'Arrodillarse' },
  { emoji: '🧑‍🦯', title: 'Bastón' },
  { emoji: '🧑‍🦼', title: 'Silla ruedas' },
  { emoji: '🦯', title: 'Apoyo' },
];

export function getDailyGif(): DailyGif {
  const randomIndex = Math.floor(Math.random() * dailyGifs.length);
  return dailyGifs[randomIndex];
}


